version: "3.8"

services:
  app:
    build: .
    container_name: scan2eat_app
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - .env
    volumes:
      - scan2eat_data:/app/data
    networks:
      - default
      - stickers_network

volumes:
  scan2eat_data:

networks:
  stickers_network:
    external: true
    name: labelstickers-api_default
